### ISSUE TITLE
feature / file-upload

### ISSUE THREAD

**Issue by syminrosie** [Mezzanine-UI/mezzanine-ui-react-hook-form#1]
[figma reference](https://www.figma.com/file/TfUTUMfSSf92EMye9VZz2t/Mezzanine-UI?node-id=0%3A22989)

<img width="397" alt="image" src="https://user-images.githubusercontent.com/43403595/189648310-0ae3ed60-1316-4cbc-ba1e-58d7a2ba6cb2.png">

- 下載按鈕要能夠 disabled，選擇是否要出現。
- 單一檔案上傳時，直接取代當下的上傳按鈕。
- 多個檔案上傳時，上傳按鈕會保留，點擊後新增會出現新的 uploadField（如上圖）
- remark 的位置會在 field 下方。
![image](https://user-images.githubusercontent.com/43403595/189874523-f24643d1-788e-4722-b96c-fdd2f63cfb51.png)

**Comment by timchen10001** [comment]
@syminrosie video 上傳 不用 preview 對吧？
如果有，那你應該分成兩個 issue 開，一個元件一個 issue 為原則。

**Comment by syminrosie** [comment]
@timchen10001 目前設計師的決議是 video 不需要 preview。

**Comment by timchen10001** [comment]
@syminrosie 下載的 api 長怎樣？
我需要更多資訊來做這個元件
以往我都是自己碰到需求自己寫，所以我大致上知道公司 backend 和 UIUX 邏輯
但這個我實在無法自己通靈，他的資料結構 input 是啥
是 link?
然後 上傳 和 下載是兩個不同概念，你期望 這個元件 給你什麼結果
你沒給我 input output

**Comment by timchen10001** [comment]
請你補完整的 test case / context

**Comment by syminrosie** [comment]
@timchen10001 
1. 跟設計師討論過後，確定目前 `JJP 上傳元件不需要下載功能`，但不確定未來其他專案會不會有（若有的話都是開新網頁（`link`）下載，）。
2. 上傳前按鈕長相如下，打開後直接選取檔案上傳。
![image](https://user-images.githubusercontent.com/43403595/192206423-d5143978-4ebf-4432-9c55-55e7f02ce5d2.png)
3. 上傳完成後會出現這樣的刪除按鈕，點擊刪除後會變成原本的上完 button，才可以上傳要取代的檔案。
![image](https://user-images.githubusercontent.com/43403595/192206708-1e6c5650-c7f7-4084-8f3c-b4b555664833.png)

如果還有需要通靈的地方的話，再麻煩跟我說一聲，我會補上 🥺

**Comment by timchen10001** [comment]
@syminrosie 我看懂了 感謝說明...

**Comment by syminrosie** [comment]
@timchen10001 我再補充一個！因為這個檔案上傳有可能很多種類，所以應該需要給出 filename 跟 fileType 🙏🏻

**Comment by timchen10001** [comment]
這個的話 元件內 會給你 resolve callback 元件不會管回傳結果也不會幫你 resolve dto
你要在不同專案下 自己 實作 resolve callback
