### ISSUE TITLE
Bug / SelectField 使用 setValue 寫入值，缺少 `shouldValidate` 導致表單無法及時知道已有值輸入

### ISSUE THREAD

**Issue by travor20814** [Mezzanine-UI/mezzanine-ui-react-hook-form#23]
參考：https://react-hook-form.com/api/useform/setvalue
相關討論：https://stackoverflow.com/questions/62532640/isvalid-is-always-false

實際情況：
使用 formState.isValid 確認表單的所有必填欄位都已填寫，但因為 SelectField 並不是使用 form 的 onChange，導致欄位變更後，表單無法知道要重新驗證。
根據官方建議，需要在 setValue 上宣告 `{ shouldValidate: true }`
```
setValue(registerName, newValue, { shouldValidate: true });
```

**Comment by timchen10001** [comment]
thx 🙏
