### ISSUE TITLE
feature / UploadImageField 是否可以吃 full-width 且等比例放大

### ISSUE THREAD

**Issue by syminrosie** [Mezzanine-UI/mezzanine-ui-react-hook-form#8]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/43403595/190352876-80321bb5-65e0-492e-b002-3b40c48be87c.png">

目前只能給 width / height 數字寫死長寬，盼能夠像 aspect-ratio 那樣吃比例放大。

**Comment by timchen10001** [comment]
```bash
    yarn add @mezzanine-ui/react-hook-form@^0.8.0 @mezzanine-ui/react-hook-form-core@^0.3.0
```
