### ISSUE TITLE
feature / UploadImageField 建議尺寸 props annotation - recommendedDimension 是否能自行填寫 string

### ISSUE THREAD

**Issue by syminrosie** [Mezzanine-UI/mezzanine-ui-react-hook-form#9]
![image](https://user-images.githubusercontent.com/43403595/190353668-7afe2680-772c-43b3-af68-d0c4fd65b8c0.png)
UploadImageField 的 建議尺寸 props annotation - recommendedDimension 只能給 array of number，但 JJP 這邊需要能夠自行填寫 string。

**Comment by timchen10001** [comment]
```bash
    yarn add @mezzanine-ui/react-hook-form@^0.8.0 @mezzanine-ui/react-hook-form-core@^0.3.0
```
